FROM python:3.9-slim-buster

WORKDIR /app

RUN mkdir -p /postgres_data

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONBUFFERED 1

RUN apt-get update \
   && apt-get -y install netcat gcc postgresql \ 
   && apt-get clean

RUN apt-get update &&\
   apt-get install -y binutils libproj-dev gdal-bin python-gdal python-gdal

RUN pip install --upgrade pip 

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app 

